### ISSUE TITLE
Double-check for revision v14

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/LilyPad_Light_Sensor#1]
1) Is proper attribution given to the original designer? [NO]
comment: I think we should add the same text about "Lilypad Concept and Shapes by: ..." text to the schematic. Just like in the protosnap plus.

2) Are junction dots used for all 3-wire connections? [YES]
comment: Yes, but this got me looking at the net D2 - is this really necessary on this small board, it was useful on the protosnap plus, but is kindof wierd to have on this smaller board

3) Is the version number correct? [YES]
comment: Yes, but I'd like to see the branch name be consistent with the schematic and board. sometimes it's wonky in revision land, but let's try to keep them all the exact same if possible.

4) Have you verified that the BOM in Sparkle is accurate (also checking for PROD_ID, NAME, VALUE, PREFIX)? [YES]
comment: BOM is good, but I'd like to see the prefixes set to U1 and R1.

5) Are measurements included for outer dimension and standoffs (Eagle layer 47)? [YES]
comment: Yes, but somehow layer 47 was turned off (aka missing from the display window options). was this the case for you?

**Comment by edspark** [comment]
All fixed. Layer 47 was turned on for me so I'm not sure what's going on there.

**Comment by lewispg228** [comment]
Looks good. Thanks @edspark !
